### ISSUE TITLE
Multiple Instances of the same music file 🎵

### ISSUE THREAD

**Issue by blackhat-coder** [twincie/max#14]
Same music file can be added to the playlist multiple times

![samesongsmultipletimes](https://user-images.githubusercontent.com/57095771/114793300-f7e11f00-9d81-11eb-89ea-3601f5b623e3.PNG)

**Comment by miraclx** [comment]
I think this is the intended behavior, no issue here!

**Comment by blackhat-coder** [comment]
Noted
